### ISSUE TITLE
Containers Broadcast Input Array Error

### ISSUE THREAD

**Issue by jsimpson746** [Dan-Patterson/tools_pro#3]
Getting the following error with the containers tool on all input FCs for this tool. Running ArcGIS Pro 2.9

Traceback (most recent call last):
  File "I:\Projects\06_WorkingFolders\Dan-Patterson-numpy_geometry-f574466\arcpro_npg\npg\tbx_tools.py", line 937, in <module>
    _tool_(tool_list)
  File "I:\Projects\06_WorkingFolders\Dan-Patterson-numpy_geometry-f574466\arcpro_npg\npg\tbx_tools.py", line 925, in _tool_
    pick_tool(tool, in_fc, out_fc, gdb, name)    # ---- run the tool
  File "I:\Projects\06_WorkingFolders\Dan-Patterson-numpy_geometry-f574466\arcpro_npg\npg\tbx_tools.py", line 804, in pick_tool
    convex_hull_polys(in_fc, gdb, name, out_kind)
  File "I:\Projects\06_WorkingFolders\Dan-Patterson-numpy_geometry-f574466\arcpro_npg\npg\tbx_tools.py", line 409, in convex_hull_polys
    g, oids, shp_kind, k, m, SR = _in_(in_fc, info)
  File "I:\Projects\06_WorkingFolders\Dan-Patterson-numpy_geometry-f574466\arcpro_npg\npg\tbx_tools.py", line 283, in _in_
    g = fc_to_Geo(in_fc, geom_kind=k, sp_ref=SR.name, info=info)
  File "I:\Projects\06_WorkingFolders\Dan-Patterson-numpy_geometry-f574466\arcpro_npg\npg\npg\npg_arc_npg.py", line 282, in fc_to_Geo
    IFT[:, :3] = IFT_
ValueError: could not broadcast input array from shape (0,) into shape (0,3)
Failed script Containers...

**Comment by Dan-Patterson** [comment]
I won't get to this until after the holidays.
Transitioning to the 2.9 toolbox format and containers got missed, sorry.
